export const ORG_MODULE_OPTIONS = 'ORG_MODULE_OPTIONS';
export const ORG_REPOSITORY = 'ORG_REPOSITORY';
export const ORG_MEMBER_REPOSITORY = 'ORG_MEMBER_REPOSITORY';
export const ORG_USER_SERVICE = 'ORG_USER_SERVICE';
