export const NOTIFICATION_LOG_REPOSITORY = 'NOTIFICATION_LOG_REPOSITORY';

export const NOTIFICATION_CHANNELS = 'NOTIFICATION_CHANNELS';

export const NOTIFICATION_QUEUE_OPTIONS = 'NOTIFICATION_QUEUE_OPTIONS';

export const NOTIFICATION_OPTIONS = 'NOTIFICATION_OPTIONS';
