export const STRIPE_MODULE_OPTIONS = 'STRIPE_MODULE_OPTIONS';
export const STRIPE_CLIENT = 'STRIPE_CLIENT';
export const STRIPE_WEBHOOK_HANDLERS = 'STRIPE_WEBHOOK_HANDLERS';
export const STRIPE_IDEMPOTENCY_CACHE = 'STRIPE_IDEMPOTENCY_CACHE';
